<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Donjon</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/normalize.css">

    <!-- Feuilles de styles de l'application -->
    <link href="https://fonts.googleapis.com/css?family=Roboto|Irish+Grover|MedievalSharp" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/base.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/layout.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/style.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/personnages.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/connexion.css">
    <link rel="stylesheet" href="<?= $wwwUrl ?>/css/members.css">

    <!-- JavaScript de l'application -->
    <script src="<?= $wwwUrl ?>/js/utilities.js"></script>
</head>
<body>

<!-- En-tête -->
<body>
    <header>
        <nav class="navbar navbar-expand-lg d-flex justify-content-between h-5">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <ul class="nav justify-content-start">
                <li class="nav-item">
                    <a class="nav-link active" href="<?= $requestUrl?>/">Actualités</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="<?= $requestUrl?>/description">Description</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Règles</a>
                </li>
            </ul>
            <ul class="nav justify-content-end">
                <?php if (isset($_SESSION["connected"])) : ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $requestUrl?>/members">
                            Espace Perso <i class="fa fa-gear" aria-hidden="true"></i>
                        </a>
                    </li>
                <?php else : ?>
                <?php endif; ?>
                <?php if (isset($_SESSION["connected"])) : ?>
                    <li class="nav-item">
                        <a  id="power-off" class="nav-link active" href="<?= $requestUrl?>/deconnexion">
                            <i class="fa fa-power-off" aria-hidden="true"></i>
                        </a>
                    </li>
                <?php else : ?>
                    <li class="nav-item">
                        <a class="nav-link" href="<?= $requestUrl?>/login">
                            <i class="fa fa-user-circle-o" aria-hidden="true"></i><em>Accès membre</em>
                        </a>
                    </li>
                <?php endif; ?>
            </ul>
        </nav>

</header>

<!-- Interface utilisateur -->

<main>
    <!-- Affichage du template lié à la vue -->
    <?php include $this->viewData['template'] ?>
</main>

<!-- Pied de page commun --><!--
<footer>
    <div class="bouton">
        <a href="#">Haut de la page</a>
    </div>
    <div class="lien">
        <i class="fa fa-facebook-square" aria-hidden="true"></i>
        <p> Donjon, le jeux de rôle</p>
        <a href="#">
            <i class="fa fa-home" aria-hidden="true"></i>
        </a>
    </div>
    <div class="contact">
        <a href="#">Accès membres</a><br/>
        <a href="#">Nous contactez</a><br/>
        <p>Site crée par Lolisicat</p>
    </div>
</footer>-->

<!-- Code principal JavaScript de l'application -->

<script
        src="https://code.jquery.com/jquery-3.3.1.js"
        integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
<script src="<?= $wwwUrl ?>/js/carousel.js"></script>
    <script src="<?= $wwwUrl ?>/js/players.js"></script>
    <script src="<?= $wwwUrl ?>/js/alert.js"></script>

</body>
</html>